name: Build and deploy to GitHub Pages

# Trigger on pushes to main (change the branch if your default branch is different)
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you need a build step (npm install / npm run build), add it here:
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build
      #   run: npm run build
      #
      # If you build to a folder (e.g. build/ or dist/), change the upload path below.

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          # change this to the output folder if you have a build step (e.g. 'build' or 'dist')
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1